### ISSUE TITLE
Merging to develop overwrites staging auth keys

### ISSUE THREAD

**Issue by andrew-jameson** [raft-tech/TANF-app#1854]
## Description
Merging to develop overwrites authentication keys/variables for staging since the defaults in CircleCI are for the dev environments.

## Action Taken

Merged to develop, log into staging

## What I expected to see
A logged in view of the app aka the Home page

## What I did see
Invalid auth token error

## Other Helpful Information

+ URL of the page I was on:
+ Browser and version:
+ Operating System: ( Windows | MacOS X | Linux | Other )
+ Is the issue repeatable?: ( yes | no | don't know )
+ Has the issue occurred more than once?:

**Comment by andrew-jameson** [comment]
Short-term workaround: Let staging use dev keys

Suboptimal workaround/solution: Write bash conditionals to skip certain keys for non-dev environments.

Potential solutions: 

- Store and retrieve auth keys from a specific s3 bucket -- will require medium lift due to retrieval/parsing within circleci and/or deployment scripts.
- Infra-as-code ala #1826 using new tool like (Terraform/Vault/SOPS/BitWarden) -- larger lift/integration/teething issues

**Comment by andrew-jameson** [comment]
Relevant code section that doesn't account for staging:
```YAML
      environment:
        description: The environment to deploy to.
        type: enum
        enum: [ "development", "production" ]
        default: development
```
https://github.com/raft-tech/TANF-app/blob/develop/.circleci/config.yml#L263
